### ISSUE TITLE
Illegal release

### ISSUE THREAD

**Issue by eAmodAdmin** [zephyrus-cr/eamod#1]
eAmod is not open for free. This is a FAKE release I am reporting to Github. Someone of my costumers uploaded it here. Please report any illegal usage on our official forums at http://www.zephysoft.com/eamod. Because of people like the one who uploaded this here, we are hardly selling one copy per month, not enough to pay our host and currently on danger to close the project.

I am the original Zephyrus from the project. You can contact me to gaiaro.staff@yahoo.com

**Comment by zephyrus-cr** [comment]
Nope. Just stop scamming people.
